[package]
name = "hash-chain"
version = "0.0.0"
authors = ["Robert <r@robertmasen.com>"]
edition = "2018"
license = "license"
repository = "https://github.com/freemasen/hash-chain"
readme = "README.md"
description = "A tiered hashmap and hashset implementation that allows for easily representing lexically scoped variables"
keywords = ["collections", "hashmap", "scope", "lexical"]
categories = ["Data structures"]

[dependencies]